
DROP TABLE IF EXISTS donation CASCADE;
DROP TABLE IF EXISTS milestone CASCADE;
DROP TABLE IF EXISTS survey CASCADE;
DROP TABLE IF EXISTS registration CASCADE;
DROP TABLE IF EXISTS eventoccurrence CASCADE;
DROP TABLE IF EXISTS eventtemplate CASCADE;
DROP TABLE IF EXISTS participant CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE participant (
    participantid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    participantemail text COLLATE pg_catalog."default" NOT NULL,
    participantfirstname text COLLATE pg_catalog."default",
    participantlastname text COLLATE pg_catalog."default",
    participantdob date,
    participantrole text COLLATE pg_catalog."default",
    participantphone text COLLATE pg_catalog."default",
    participantcity text COLLATE pg_catalog."default",
    participantstate text COLLATE pg_catalog."default",
    participantzip text COLLATE pg_catalog."default",
    participantschooloremployer text COLLATE pg_catalog."default",
    participantfieldofinterest text COLLATE pg_catalog."default",
    CONSTRAINT participant_pkey PRIMARY KEY (participantid),
    CONSTRAINT participant_participantemail_key UNIQUE (participantemail)
);

CREATE TABLE eventtemplate (
    eventtemplateid integer NOT NULL,
    eventname text COLLATE pg_catalog."default" NOT NULL,
    eventtype text COLLATE pg_catalog."default",
    eventdescription text COLLATE pg_catalog."default",
    eventrecurrencepattern text COLLATE pg_catalog."default",
    eventdefaultcapacity integer,
    CONSTRAINT eventtemplate_pkey PRIMARY KEY (eventtemplateid),
    CONSTRAINT eventtemplate_eventname_key UNIQUE (eventname)
);

CREATE TABLE eventoccurrence (
    eventoccurrenceid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    eventtemplateid integer NOT NULL,
    eventname text COLLATE pg_catalog."default" NOT NULL,
    eventdatetimestart timestamp without time zone NOT NULL,
    eventdatetimeend timestamp without time zone,
    eventlocation text COLLATE pg_catalog."default",
    eventcapacity integer,
    eventregistrationdeadline timestamp without time zone,
    CONSTRAINT eventoccurrence_pkey PRIMARY KEY (eventoccurrenceid),
    CONSTRAINT eventoccurrence_eventtemplateid_fkey FOREIGN KEY (eventtemplateid)
        REFERENCES public.eventtemplate (eventtemplateid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE registration (
    registrationid integer NOT NULL,
    participantid integer NOT NULL,
    eventoccurrenceid integer NOT NULL,
    registrationstatus text COLLATE pg_catalog."default",
    registrationattendedflag smallint,
    registrationcheckintime timestamp without time zone,
    registrationcreatedat timestamp without time zone,
    CONSTRAINT registration_pkey PRIMARY KEY (registrationid),
    CONSTRAINT registration_eventoccurrenceid_fkey FOREIGN KEY (eventoccurrenceid)
        REFERENCES public.eventoccurrence (eventoccurrenceid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT registration_participantid_fkey FOREIGN KEY (participantid)
        REFERENCES public.participant (participantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE survey (
    surveyid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    participantid integer NOT NULL,
    eventoccurrenceid integer NOT NULL,
    surveysatisfactionscore integer,
    surveyusefulnessscore integer,
    surveyinstructorscore integer,
    surveyrecommendationscore integer,
    surveynpsbucket text COLLATE pg_catalog."default",
    surveycomments text COLLATE pg_catalog."default",
    surveysubmissiondate timestamp without time zone,
    surveyoverallscore numeric(5,2) GENERATED ALWAYS AS (round((((((COALESCE(surveysatisfactionscore, 0) + COALESCE(surveyusefulnessscore, 0)) + COALESCE(surveyinstructorscore, 0)) + COALESCE(surveyrecommendationscore, 0)))::numeric / (NULLIF((((((surveysatisfactionscore IS NOT NULL))::integer + ((surveyusefulnessscore IS NOT NULL))::integer) + ((surveyinstructorscore IS NOT NULL))::integer) + ((surveyrecommendationscore IS NOT NULL))::integer), 0))::numeric), 2)) STORED,
    CONSTRAINT survey_pkey PRIMARY KEY (surveyid),
    CONSTRAINT survey_eventoccurrenceid_fkey FOREIGN KEY (eventoccurrenceid)
        REFERENCES public.eventoccurrence (eventoccurrenceid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT survey_participantid_fkey FOREIGN KEY (participantid)
        REFERENCES public.participant (participantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE milestone (
    milestoneid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    participantid integer NOT NULL,
    milestonetitle text COLLATE pg_catalog."default" NOT NULL,
    milestonedate date NOT NULL,
    CONSTRAINT milestone_pkey PRIMARY KEY (milestoneid),
    CONSTRAINT milestone_participantid_fkey FOREIGN KEY (participantid)
        REFERENCES public.participant (participantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE donation (
    donationid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    participantid integer NOT NULL,
    donationdate date NOT NULL,
    donationamount numeric(10,2) NOT NULL,
    CONSTRAINT donation_pkey PRIMARY KEY (donationid),
    CONSTRAINT donation_participantid_fkey FOREIGN KEY (participantid)
        REFERENCES public.participant (participantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE users (
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying(7) COLLATE pg_catalog."default" NOT NULL,
    created_date date NOT NULL DEFAULT CURRENT_DATE,
    full_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
